apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: skillfybank
  labels:
    app: notification-service
spec:
  type: LoadBalancer
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
