apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-pvc
  namespace: skillfybank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
