apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: skillfybank-tracing
  namespace: skillfybank
spec:
  tracing:
  - providers:
    - name: jaeger
    randomSamplingPercentage: 100.0
